#Makefile for "second in class" CS2600

CC = gcc

employee1: src\\employeeMain.c src\\employeeOne.c src\\employeeTable.c
	$(CC) -o bin\\one src\\employeeMain.c src\\employeeOne.c src\\employeeTable.c

employee2: src\\employeeMain.c src\\employeeTwo.c src\\employeeTable.c
	$(CC) -o bin\\two src\\employeeMain.c src\\employeeTwo.c src\\employeeTable.c

loshu: src\\LoShu.c
	$(CC) -o bin\\LoShu src\\LoShu.c
